### ISSUE TITLE
Why does this create generate `const`s instead of `static`s?

### ISSUE THREAD

**Issue by kije** [Eolu/const-gen#10]
Hi, first off, thanks for this great crate, it makes defining compile-time constants much more ergonomic.

However, I was wondering why the crate generates `const`  instead of `static`s?  
It's my understanding that `const`s will get inlined by the compiler to their use sites, hence creating potentially a lot of duplication and overhead.

`static`s on the other hand would get put in a dedicates section in the binary and thus not produce this duplication/overhead. I would assume most use cases for compile-time defined constants would want the behavior of `static`s instead of `const`s.

So I was wondering if that was a conscious decision, and if so what are the reasons behind it?

Also, would you be open to a PR that would implement a `const_gen::static_declaration` macro that would generate a `static`?
From what I saw this should be fairly easy to implement and would give the users the choice if they want `const`s or `static`s

**Comment by Eolu** [comment]
Thanks for the feedback!

This was a conscious decision. There's a tradeoff in the choice between `const` and `static` - `static` has the benefit you mentioned of taking only one dedicated place in memory, but has the drawback that accessing takes one extra dereference when compared to `const`. `const` is a minor hit to compile-time and binary size at the gain of runtime efficiency, which is very useful for constants that are referenced often but in few places.

That said, I can see the argument that for constants referenced infrequently but in many places, `static` may be the better choice. Thus, a PR implementing `const_gen::static_declaration` seems like an obvious improvement to this crate and I am 100% open to it.

**Comment by kije** [comment]
@Eolu great, thanks for elaborating the reasons behind the decision. 

Perfect, I'll prepare a PR then 👍

**Comment by kije** [comment]
@Eolu [PR](https://github.com/Eolu/const-gen/pull/11) is prepared

**Comment by Eolu** [comment]
Officially published as version 1.5.0. Thanks for the work! Closing issue.
