### ISSUE TITLE
The fields of a generated public struct aren't public

### ISSUE THREAD

**Issue by oriki195** [Eolu/const-gen#7]
While using the following build struct to create a configuration struct:
```rust
#[derive(CompileConst)]
struct Config {
    pub a: usize,
    pub b: String,
}
```

Then using in build.rs:
```rust
const_definition!(#[derive(Debug)] pub Config);
```
Creates a struct:
```rust
#[derive(Debug)]
pub struct Config {
    a: usize,
    b: String,
}
```

The struct is then rendered useless because you cant access its fields.
Would like to be able to also make the fields public.

**Comment by Eolu** [comment]
This has been fixed in version 1.2.0
